Sentry(Hotfix): Fixed NoMethodError: undefined method `dimension' for nil:NilClass (#5575)
* Fixed assessment not found error

* Loading factors directly

* Reverting changes to remove owner check and added check for superadmin

* Return ActiveRecord::Relation from records if there are not factor instead of nil

---------

Co-authored-by: Rohan <rohanpujaris@gmail.com>